### ISSUE TITLE
Space before ellipsis when break_word is false

### ISSUE THREAD

**Issue by julkue** [glinford/ellipsis.js#12]
When `break_word` is `false` it adds a space after the last word, e.g. `"Hello …"`. This space should be part of the option property `ellipsis` and not be added automatically.

**Comment by julkue** [comment]
Closing without any comment @glinford ?

**Comment by glinford** [comment]
Feel free to do a PR and add it as an option.
The space between the break word is false is my decision on how should ellipsis be used.
(Hell... or Hello ...), if you want to add it as an option feel free to PR @julmot
