### ISSUE TITLE
Conflict with YUI minificator

### ISSUE THREAD

**Issue by patocardo** [glinford/ellipsis.js#16]
YUI minificator creates a conflict with Ellipsis. It happens with the 'class' property, we gave a temporal solution by using 'class' and ['class'] in each appearence of the property, but they should renamed to keep consistance

**Comment by svenzimmermann** [comment]
Can you give us a new master with fixes. Chrome and IE is not responsive with actual master.

**Comment by patocardo** [comment]
I don't have permissions here to push to master. If someone can set a new branch, I would be pleased to upload the changes I suggest

**Comment by glinford** [comment]
I'll rename class for className, and push a fix.

**Comment by glinford** [comment]
class renamed to className in 0.1.3
https://www.npmjs.com/package/ellipsis.js
