### ISSUE TITLE
Crashing IE 9

### ISSUE THREAD

**Issue by xremix** [glinford/ellipsis.js#9]
It seems the latest version of the library is crashing the IE 9 because of "site is not responding due to a long-running script.". 
I checked older versions as the demo site seems to work and the latest version without having the issue occurring for me was:
https://github.com/glinford/ellipsis.js/tree/bd192fa62cfff1a3eb40d72b31ae2285a61ab87d

Also when trying to pause the code in the debugger of the developer tools right before the browser crashes it showed the same line loading that has been added after the code started to crash:
https://github.com/glinford/ellipsis.js/commit/c6363e44cd232e64cc4daa310d0b36dcab7537f4

Let me know if you need any additional information.

**Comment by donut** [comment]
I ran into an issue with Chrome becoming indefinitely unresponsive (just the tab it's running in). I'm guessing it's related. Since I don't need a generalized solution, I'm rolling my own.

**Comment by xremix** [comment]
@glinford any idea on merging this?
